"""RQ2 reproducibility ladder (PROTOCOL Secs. 1/4/6/7, block D).

Question: given byte-identical inputs, how reproducible are the controller's
decisions and outputs across serving configurations, and what do the exposed
determinism controls actually do?

Probe states are REAL block-C states, not synthetic (S01 D-045 lesser finding;
PROTOCOL Sec. 6): each sampled state is regenerated by replaying a block-C
episode's recorded decision sidecar through the deterministic plant, which
reproduces byte-for-byte the observation/history prompt the controller saw at
that instant. Replay fidelity is verified per episode by exact match of the
replayed metrics against the recorded sweep.jsonl row; episodes that do not
replay exactly (e.g. an API-error retry whose latency was not recorded) are
excluded from sampling and counted.

Serving configurations (PROTOCOL Sec. 4 ladder, v1.3b sizing):
  local-serial    llama-server :8200, --parallel 1, temperature 0, seed 42
  local-batched   llama-server :8200, --parallel 4, temperature 0, seed 42,
                  repeats fired in concurrent waves of 4 (continuous batching on)
  luna-default    gpt-5.6-luna, vendor-default sampling, no seed
  luna-seeded     gpt-5.6-luna, seed=42 (the documented determinism control)
  sonnet-default  claude-sonnet-5, vendor-default sampling

A sonnet-pinned rung was pre-registered (PROTOCOL Sec. 4 ladder) and is
UNRUNNABLE: claude-sonnet-5 rejects temperature != 1, top_k, and top_p with
HTTP 400 "deprecated for this model" — the vendor exposes no determinism
control at all for its newest generation. Probed mechanically by
`rq2.py probe-controls` (artifact: results/rq2_determinism_probe.json);
PROTOCOL Sec. 13 v1.4; DECISIONS D-016. The missing rung is a finding, not
a gap: the reproducibility ladder's hosted rungs are default-sampling only
for this vendor, and the released evidence records exactly that.

Repeats: 30 per state for local + luna configs, 20 for sonnet (v1.3b last
reduction step). max_tokens matches the sweep (hosted 300 / local 400) so the
prompt-economics regime is identical to block C.

Metrics per (config, state): byte-identity rate (modal raw output share),
decision-identity rate (modal (replicas, variant) share), normalised entropy of
the scale direction {up, hold, down} vs the state's current replicas,
Delta-replicas dispersion (max-min), self-contradiction rate (both up and down
seen for the same input), parse-failure count. Computed in analyze.py from the
raw rq2.jsonl; this script only records evidence.

Usage:
  python3 rq2.py sample                      # replay C sidecars -> rq2_states.json
  python3 rq2.py hosted [--config NAME]      # luna/sonnet configs (API spend)
  python3 rq2.py local-serial                # needs :8200 with --parallel 1
  python3 rq2.py local-batched               # needs :8200 with --parallel 4
  python3 rq2.py selfcheck                   # offline; no API, no server

Resume-safe: results/rq2.jsonl keyed (config, state_id, repeat); existing keys
are skipped. Hosted spend goes through the same SpendLedger ($60 backstop).
"""
from __future__ import annotations

import argparse
import gzip
import json
import time
import urllib.request
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

from artifact_io import append_jsonl, write_json
from fairness import build_cal, episode_cfg, load_design
from llm_controllers import (LEDGER, RESPONSE_SPEC, call_cost_usd, make_intent,
                             parse_action, render_history, render_observation,
                             _anthropic_call, _local_call, _openai_call)
from plant import Action, Plant
from sweep import menu_text
from workload import make_trace

STUDY = Path(__file__).resolve().parents[1]
DECDIR = STUDY / "results" / "decisions"
SWEEP = STUDY / "results" / "sweep.jsonl"
STATES = STUDY / "results" / "rq2_states.json"
OUT = STUDY / "results" / "rq2.jsonl"

N_STATES = 30
REPEATS = {"local-serial": 30, "local-batched": 30,
           "luna-default": 30, "luna-seeded": 30,
           "sonnet-default": 20}
LOCAL_PORT = 8200
PROBE_OUT = STUDY / "results" / "rq2_determinism_probe.json"

# ------------------------------------------------------------------ replay

class ReplayController:
    """Feeds an episode's recorded actions back to the plant and captures the
    byte-identical (observation, history) prompt at every decision instant."""
    name = "replay"

    def __init__(self, groups: list[dict]):
        self.groups = groups          # one entry per decision instant, in order
        self.idx = 0
        self.captured: list[dict] = []
        self.mismatch = False

    def decide(self, obs, history) -> Action:
        if self.idx >= len(self.groups):
            self.mismatch = True      # plant asked for more decisions than recorded
            return Action(replicas=obs.replicas, variant=obs.variant, parse_failed=True)
        g = self.groups[self.idx]
        self.idx += 1
        if abs(g["t"] - obs.t) > 1e-6:
            self.mismatch = True
        act = g["action"]
        if act is None:               # recorded parse failure -> fallback hold
            act = Action(replicas=obs.replicas, variant=obs.variant, parse_failed=True)
        act.latency_s = g["latency_s"]
        act.tokens_in, act.tokens_out, act.usd = g["tokens_in"], g["tokens_out"], g["usd"]
        self.captured.append({
            "t": obs.t,
            "user": render_observation(obs) + "\n" + render_history(history),
            "obs": {"replicas": obs.replicas, "variant": obs.variant,
                    "queue_len": obs.queue_len, "p95_ms": obs.p95_ms,
                    "utilization": obs.utilization,
                    "arrival_rate": obs.arrival_rate},
        })
        return act


def group_sidecar(entries: list[dict]) -> tuple[list[dict], bool]:
    """Group per-call sidecar entries into per-decision records, replicating
    LLMController.decide: attempts at the same t, first parseable wins; latency
    is the sum across attempts. Returns (groups, clean); clean=False if any
    attempt lacks a recorded latency (API-error entries) so replay would drift."""
    groups: list[dict] = []
    clean = True
    for e in entries:
        if not groups or abs(e["t"] - groups[-1]["t"]) > 1e-9 or groups[-1]["done"]:
            if groups and not groups[-1]["done"]:
                pass                  # previous decision ended in parse failure
            if groups and abs(e["t"] - groups[-1]["t"]) <= 1e-9 and groups[-1]["done"]:
                clean = False         # extra call at same t after success: unexpected
            groups.append({"t": e["t"], "action": None, "latency_s": 0.0,
                           "tokens_in": 0, "tokens_out": 0, "usd": 0.0,
                           "done": False})
        g = groups[-1]
        if "latency_s" in e:
            g["latency_s"] += e["latency_s"]
        else:
            clean = False             # error entry without recorded latency
        g["usd"] += e.get("usd", 0.0)
        u = (e.get("meta") or {}).get("usage") or {}
        g["tokens_in"] += u.get("prompt_tokens") or 0
        g["tokens_out"] += u.get("completion_tokens") or 0
        if "raw" in e and not g["done"]:
            try:
                g["action"] = parse_action(e["raw"], None)
                g["done"] = True
            except Exception:
                pass
    for g in groups:
        g.pop("done", None)
    return groups, clean


def replay_episode(design, cal, row: dict) -> ReplayController | None:
    """Replay one block-C episode from its sidecar; return the controller with
    captured prompts iff the replayed metrics exactly match the recorded row."""
    sidecar = DECDIR / (row["key"].replace("|", "_") + ".json.gz")
    if not sidecar.exists():
        return None
    with gzip.open(sidecar, "rt") as f:
        entries = json.load(f)
    groups, clean = group_sidecar(entries)
    if not clean:
        return None
    cfg = episode_cfg(design, float(row["cadence_s"]))
    arrivals, _ = make_trace(design["mean_rate_rps"], row["I"], cfg.horizon_s,
                             row["seed"])
    ctl = ReplayController(groups)
    plant = Plant(cal, cfg, plant_seed=row["seed"])
    m = plant.run(list(arrivals), ctl, init_replicas=design["init_replicas"],
                  init_variant=design["init_variant"])
    rec = row["metrics"]
    exact = (not ctl.mismatch
             and abs(m["U_S03"] - rec["U_S03"]) < 1e-9
             and m["offered"] == rec["offered"]
             and m["completed"] == rec["completed"]
             and m["controller"]["invocations"] == rec["controller"]["invocations"])
    return ctl if exact else None


# ------------------------------------------------------------------ sampling

def stratum_of(obs: dict, slo_ms: float) -> str:
    """Mechanical strata (fixed before sampling): near-threshold states sit at
    the decision boundary (p95 within +-20% of SLO, or utilisation 0.75-0.95);
    clear-cut states are unambiguous (deep overload or deep calm); the rest are
    'other' and not sampled."""
    p95, util, q = obs["p95_ms"], obs["utilization"], obs["queue_len"]
    if p95 is not None and 0.8 * slo_ms <= p95 <= 1.2 * slo_ms:
        return "near"
    if 0.75 <= util <= 0.95:
        return "near"
    if (p95 is not None and p95 > 1.5 * slo_ms) or q >= 20:
        return "clear-overload"
    if (p95 is None or p95 < 0.5 * slo_ms) and q == 0 and util < 0.5:
        return "clear-calm"
    return "other"


def cmd_sample(design, cal) -> None:
    rows = []
    for line in SWEEP.read_text().splitlines():
        try:
            r = json.loads(line)
        except Exception:
            continue
        if r.get("block") == "C" and r.get("model") == "gpt-5.6-luna":
            rows.append(r)
    print(f"{len(rows)} luna block-C episodes on disk")
    system = make_intent("full", slo_ms=design["slo_ms"], abandon_s=design["abandon_s"],
                         max_replicas=design["max_replicas"],
                         variant_menu=menu_text(design),
                         switch_s=max(design["switch_load_s"].values())
                         ) + "\n\n" + RESPONSE_SPEC
    pool = {"near": [], "clear-overload": [], "clear-calm": []}
    replayed = failed = 0
    for row in rows:
        ctl = replay_episode(design, cal, row)
        if ctl is None:
            failed += 1
            continue
        replayed += 1
        for cap in ctl.captured:
            if cap["t"] < design["warmup_exclude_s"]:
                continue              # scored span only (R6)
            s = stratum_of(cap["obs"], design["slo_ms"])
            if s in pool:
                pool[s].append({**cap, "stratum": s, "episode_key": row["key"],
                                "I": row["I"], "cadence_s": row["cadence_s"]})
    print(f"replayed exactly: {replayed}; excluded (non-exact/missing): {failed}")
    for s, lst in pool.items():
        print(f"  stratum {s}: {len(lst)} candidate states")
    # Deterministic spread: 15 near, 8 clear-overload, 7 clear-calm; within each
    # stratum spread across (I, cadence) round-robin, then evenly by index.
    import random as _random
    rng = _random.Random(20260802)
    quota = {"near": 15, "clear-overload": 8, "clear-calm": 7}
    chosen = []
    for s, n in quota.items():
        cands = pool[s]
        if not cands:
            print(f"  WARNING: stratum {s} empty — quota unmet (reported, not hidden)")
            continue
        bycell: dict = {}
        for c in cands:
            bycell.setdefault((c["I"], c["cadence_s"]), []).append(c)
        for lst in bycell.values():
            rng.shuffle(lst)
        cells = sorted(bycell)
        i = 0
        while sum(1 for c in chosen if c["stratum"] == s) < min(n, len(cands)):
            cell = cells[i % len(cells)]
            if bycell[cell]:
                chosen.append(bycell[cell].pop())
            i += 1
            if i > 10000:
                break
    for k, c in enumerate(chosen):
        c["state_id"] = f"st{k:02d}"
    art = {"system": system,
           "replayed_ok": replayed, "replay_excluded": failed,
           "pool_sizes": {s: len(l) for s, l in pool.items()},
           "quota": quota, "states": chosen}
    write_json(STATES, art)
    print(f"wrote {len(chosen)} states -> {STATES.name}")


# ------------------------------------------------------------------ repeats

def server_slots(port: int = LOCAL_PORT) -> int:
    with urllib.request.urlopen(f"http://127.0.0.1:{port}/props", timeout=5) as r:
        props = json.load(r)
    n = props.get("total_slots") or props.get("n_parallel") \
        or (props.get("default_generation_settings") or {}).get("n_parallel")
    if n is None:
        raise RuntimeError(f"cannot determine slot count from /props: {props}")
    return int(n)


def one_call(config: str, system: str, user: str) -> dict:
    """One repeat. Transient API errors are retried (the sweep's known luna
    HTTP-400 flake killed the first hosted run — chain log 2026-08-03); a call
    still failing after retries is RECORDED as an errored row, never raised —
    API errors are a counted failure mode (PROTOCOL Sec. 8b), and one flake
    must not kill a 2,400-call config."""
    t0 = time.monotonic()
    text = meta = None
    last_err = None
    for attempt in range(3):
        try:
            if config == "luna-default":
                text, meta = _openai_call("gpt-5.6-luna", system, user, seed=None)
            elif config == "luna-seeded":
                text, meta = _openai_call("gpt-5.6-luna", system, user, seed=42)
            elif config == "sonnet-default":
                text, meta = _anthropic_call("claude-sonnet-5", system, user, seed=None)
            elif config in ("local-serial", "local-batched"):
                text, meta = _local_call("local-3B", system, user, seed=42,
                                         port=LOCAL_PORT, temperature=0.0)
            else:
                raise ValueError(config)
            break
        except ValueError:
            raise
        except Exception as e:
            last_err = str(e)
            time.sleep(min(4.0, 2.0 ** attempt))
    latency = time.monotonic() - t0
    if text is None:
        return {"raw": None, "meta": None, "latency_s": latency, "usd": 0.0,
                "parsed": None, "parse_error": None,
                "api_error": f"failed after 3 attempts: {last_err}"}
    usd = 0.0
    if config.startswith(("luna", "sonnet")):
        billed = "gpt-5.6-luna" if config.startswith("luna") else "claude-sonnet-5"
        usd = call_cost_usd(billed, meta.get("usage") or {})
        if usd > 0:
            LEDGER.add(billed, usd)
    parsed = None
    err = None
    try:
        a = parse_action(text, None)
        parsed = {"replicas": a.replicas, "variant": a.variant,
                  "repaired": a.repaired}
    except Exception as e:
        err = str(e)
    return {"raw": text, "meta": meta, "latency_s": latency, "usd": usd,
            "parsed": parsed, "parse_error": err}


def existing() -> set:
    keys = set()
    if OUT.exists():
        for line in OUT.read_text().splitlines():
            try:
                keys.add(json.loads(line)["key"])
            except Exception:
                continue
    return keys


def record(key: str, payload: dict) -> None:
    payload["key"] = key
    append_jsonl(OUT, payload)


def run_config(config: str, parallel: int = 1) -> None:
    art = json.loads(STATES.read_text())
    system, states = art["system"], art["states"]
    done = existing()
    jobs = [(s, rep) for s in states for rep in range(REPEATS[config])
            if f"{config}|{s['state_id']}|r{rep}" not in done]
    print(f"{config}: {len(jobs)} calls to run "
          f"({len(states)} states x {REPEATS[config]} repeats, minus done)")

    def run_one(job):
        s, rep = job
        res = one_call(config, system, s["user"])
        return f"{config}|{s['state_id']}|r{rep}", {
            "config": config, "state_id": s["state_id"], "repeat": rep,
            "stratum": s["stratum"], "episode_key": s["episode_key"],
            "t": s["t"], **res}

    if parallel <= 1:
        for job in jobs:
            key, payload = run_one(job)
            record(key, payload)
    else:
        # waves of `parallel` so batched slots genuinely co-schedule
        for i in range(0, len(jobs), parallel):
            wave = jobs[i:i + parallel]
            with ThreadPoolExecutor(max_workers=parallel) as ex:
                for key, payload in ex.map(run_one, wave):
                    record(key, payload)
            if (i // parallel) % 20 == 0:
                print(f"  {min(i + parallel, len(jobs))}/{len(jobs)}", flush=True)
    print(f"{config} complete")


# ------------------------------------------------------------------ probe

def cmd_probe_controls() -> None:
    """Record, as a committed artifact, which sampling/determinism controls each
    hosted model under study actually accepts (RQ2: 'what do the exposed
    determinism controls actually do' begins with 'which ones exist'). Each probe
    is one minimal real call; rejections are captured verbatim."""
    import urllib.error

    def probe(vendor: str, extra: dict) -> dict:
        sys_p = "Reply with the single word: ok"
        try:
            if vendor == "openai":
                body = {"model": "gpt-5.6-luna", "max_completion_tokens": 20,
                        "messages": [{"role": "system", "content": sys_p},
                                     {"role": "user", "content": "go"}], **extra}
                req = urllib.request.Request(
                    "https://api.openai.com/v1/chat/completions",
                    data=json.dumps(body).encode(),
                    headers={"Content-Type": "application/json",
                             "Authorization": f"Bearer {__import__('os').environ['OPENAI_API_KEY']}"})
            else:
                body = {"model": "claude-sonnet-5", "max_tokens": 20,
                        "system": sys_p,
                        "messages": [{"role": "user", "content": "go"}], **extra}
                req = urllib.request.Request(
                    "https://api.anthropic.com/v1/messages",
                    data=json.dumps(body).encode(),
                    headers={"Content-Type": "application/json",
                             "x-api-key": __import__('os').environ["ANTHROPIC_API_KEY"],
                             "anthropic-version": "2023-06-01"})
            with urllib.request.urlopen(req, timeout=60) as r:
                payload = json.load(r)
            return {"vendor": vendor, "params": extra, "accepted": True,
                    "model_id": payload.get("model"),
                    "usage": payload.get("usage", {})}
        except urllib.error.HTTPError as e:
            try:
                err = json.loads(e.read()).get("error", {}).get("message", "")
            except Exception:
                err = "<unreadable body>"
            return {"vendor": vendor, "params": extra, "accepted": False,
                    "http_status": e.code, "error_message": err}

    probes = [
        ("openai", {}), ("openai", {"seed": 42}), ("openai", {"temperature": 0.0}),
        ("openai", {"temperature": 1.0}), ("openai", {"top_p": 0.01}),
        ("anthropic", {}), ("anthropic", {"temperature": 0.0}),
        ("anthropic", {"temperature": 0.5}), ("anthropic", {"temperature": 1}),
        ("anthropic", {"top_k": 1}), ("anthropic", {"top_p": 0.01}),
    ]
    results = [probe(v, p) for v, p in probes]
    art = {"purpose": "Which exposed sampling/determinism controls each hosted "
                      "model under study accepts (PROTOCOL Sec. 4 ladder, v1.4; "
                      "D-016). One minimal real call per row; rejections verbatim.",
           "results": results}
    write_json(PROBE_OUT, art)
    for r in results:
        tag = "ACCEPTED" if r["accepted"] else f"HTTP {r['http_status']}: {r['error_message']}"
        print(f"{r['vendor']:>9} {json.dumps(r['params']):<22} -> {tag}")
    print(f"wrote {PROBE_OUT.name}")


# ------------------------------------------------------------------ selfcheck

def cmd_selfcheck(design, cal) -> None:
    """Offline: the replay harness must reproduce a scripted episode exactly,
    and the stratum classifier must behave at its boundaries."""
    cfg = episode_cfg(design, 60.0)
    arrivals, _ = make_trace(design["mean_rate_rps"], 400.0, cfg.horizon_s, 424242)

    class Scripted:
        name = "scripted"
        def __init__(self):
            self.log = []
        def decide(self, obs, history):
            r = 1 + (int(obs.t) // 300) % 3
            v = ["tiny-1B4", "full-3B", "lite-1B"][(int(obs.t) // 600) % 3]
            raw = json.dumps({"replicas": r, "variant": v, "why": "scripted"})
            self.log.append({"t": obs.t, "attempt": 0, "raw": raw,
                             "meta": {"usage": {"prompt_tokens": 10,
                                                "completion_tokens": 5}},
                             "latency_s": 1.5, "usd": 0.0})
            a = Action(replicas=r, variant=v, raw=raw)
            a.latency_s = 1.5
            return a

    sc = Scripted()
    m1 = Plant(cal, cfg, plant_seed=424242).run(
        list(arrivals), sc, design["init_replicas"], design["init_variant"])
    groups, clean = group_sidecar(sc.log)
    assert clean and len(groups) == m1["controller"]["invocations"]
    ctl = ReplayController(groups)
    m2 = Plant(cal, cfg, plant_seed=424242).run(
        list(arrivals), ctl, design["init_replicas"], design["init_variant"])
    assert not ctl.mismatch
    assert abs(m1["U_S03"] - m2["U_S03"]) < 1e-12, (m1["U_S03"], m2["U_S03"])
    assert m1["offered"] == m2["offered"] and m1["completed"] == m2["completed"]
    assert len(ctl.captured) == len(groups)
    assert all("STATE t=" in c["user"] for c in ctl.captured)
    # parse-failure grouping: two failed attempts then one success at same t
    bad = [{"t": 60.0, "attempt": 0, "raw": "gibberish", "latency_s": 1.0,
            "meta": {"usage": {}}, "usd": 0.0},
           {"t": 60.0, "attempt": 1, "raw": '{"replicas": 3, "variant": "full-3B", '
            '"why": "ok"}', "latency_s": 2.0, "meta": {"usage": {}}, "usd": 0.0}]
    g2, clean2 = group_sidecar(bad)
    assert clean2 and len(g2) == 1 and g2[0]["action"].replicas == 3
    assert abs(g2[0]["latency_s"] - 3.0) < 1e-12
    # stratum boundaries
    slo = design["slo_ms"]
    assert stratum_of({"p95_ms": slo, "utilization": 0.2, "queue_len": 0}, slo) == "near"
    assert stratum_of({"p95_ms": 2 * slo, "utilization": 1.0, "queue_len": 50},
                      slo) == "clear-overload"
    assert stratum_of({"p95_ms": None, "utilization": 0.1, "queue_len": 0},
                      slo) == "clear-calm"
    assert stratum_of({"p95_ms": 0.6 * slo, "utilization": 0.6, "queue_len": 2},
                      slo) == "other"
    print("rq2 offline self-checks PASS (replay exact; grouping; strata)")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("cmd", choices=["sample", "hosted", "local-serial",
                                    "local-batched", "selfcheck", "probe-controls"])
    ap.add_argument("--config", default=None,
                    help="hosted only: run a single named config")
    args = ap.parse_args()
    design = load_design()
    cal = build_cal(design)
    if args.cmd == "sample":
        cmd_sample(design, cal)
    elif args.cmd == "selfcheck":
        cmd_selfcheck(design, cal)
    elif args.cmd == "probe-controls":
        cmd_probe_controls()
    elif args.cmd == "hosted":
        configs = ([args.config] if args.config else
                   ["luna-seeded", "luna-default", "sonnet-default"])
        for c in configs:
            run_config(c, parallel=4)
    elif args.cmd == "local-serial":
        n = server_slots()
        assert n == 1, f"local-serial needs --parallel 1 server, found {n} slots"
        run_config("local-serial", parallel=1)
    elif args.cmd == "local-batched":
        n = server_slots()
        assert n == 4, f"local-batched needs --parallel 4 server, found {n} slots"
        run_config("local-batched", parallel=4)


if __name__ == "__main__":
    import os
    try:
        from dotenv import load_dotenv
    except ModuleNotFoundError:
        pass
    else:
        load_dotenv(Path(__file__).resolve().parents[3] / ".env")
    main()
